config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    resources :wishlists, only: [ :create, :destroy ]
  end

  resources :properties, only: [ :show ] do
    resources :bookings, only: [ :new ]
  end

  resources :booking_payments, only: [ :create ]

  resources :wishlists, only: [ :index ]

  resource :profile, only: [ :edit, :update ]
  resource :email, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]

  resources :reservations, only: [ :index ] do
    resources :reviews, only: [ :new, :create ]
  end

  get "/search", to: "search#index"

  namespace :owner do
    resources :properties do
      member do
        patch :update_location
        patch :update_amenities
        patch :add_images
        delete :remove_image
      end
    end
    resources :reservations, only: [ :index ]
  end

  get "booking_payments/success", to: "booking_payments#success"
end

app/models/property.rb
class Property < ApplicationRecord
  validates :name, presence: :true
  validates :headline, presence: :true
  validates :description, presence: :true
  validates :address_1, presence: :true
  validates :city, presence: :true
  validates :state, presence: :true
  validates :country_code, presence: :true
  validates :latitude, presence: :true
  validates :longitude, presence: :true

  monetize :price_cents, allow_nil: true

  has_many_attached :images

  has_many :reviews, dependent: :destroy

  has_many :property_amenities, dependent: :destroy
  has_many :amenities, through: :property_amenities, source: :amenity, dependent: :destroy

  has_many :wishlists, dependent: :destroy
  has_many :wishlisted_users, through: :wishlists, source: :user, dependent: :destroy

  has_many :reservations, dependent: :destroy
  has_many :reserved_users, through: :reservations, source: :user, dependent: :destroy

  has_many :payments, through: :reservations, dependent: :destroy

  has_rich_text :description

  def self.with_reservation_overlap(checkin_date, checkout_date)
    where.not(id: Reservation.overlapping_reservation(checkin_date, checkout_date).pluck(:property_id))
  end

  def update_average_rating
    average_rating = reviews.average(:final_rating)
    update_column(:average_final_rating, average_rating)
  end

  def average_cleanliness_rating
    reviews.average(:cleanliness_rating)
  end

  def average_accuracy_rating
    reviews.average(:accuracy_rating)
  end

  def average_checkin_rating
    reviews.average(:checkin_rating)
  end

  def average_communication_rating
    reviews.average(:communication_rating)
  end

  def average_location_rating
    reviews.average(:location_rating)
  end

  def average_value_rating
    reviews.average(:value_rating)
  end

  def wishlisted_by?(user = nil)
    return if user.nil?

    wishlisted_users.include?(user)
  end

  def available_dates
    next_reservation = reservations.upcoming_reservations.first
    current_reservation = reservations.current_reservations.first

    if current_reservation.nil? && next_reservation.nil?
      Date.tomorrow.strftime("%e %b")..(Date.tomorrow + 30.days).strftime("%e %b")
    elsif current_reservation.nil?
      Date.tomorrow.strftime("%e %b")..next_reservation.checkin_date.strftime("%e %b")
    elsif next_reservation.nil?
      current_reservation.checkout_date.strftime("%e %b")..(Date.tomorrow + 30.days).strftime("%e %b")
    else
      current_reservation.checkout_date.strftime("%e %b")..next_reservation.checkin_date.strftime("%e %b")
    end
  end
end

app/controllers/owner/dashboard_controller.rb
module Owner
  class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
    end
  end
end

app/controllers/owner/properties_controller.rb
module Owner
  class PropertiesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_property, only: [ :edit, :update, :update_amenities, :update_location, :add_images, :remove_image, :destroy ]

    def index
      @properties = current_user.properties.order(created_at: :desc)
    end

    def new
      @property = Property.new
    end

    def create
      @property = current_user.properties.create!(property_params)

      redirect_to edit_owner_property_path(@property), notice: "Property added successfully"
    end

    def update
      if @property.update!(property_params)
        redirect_to edit_owner_property_path, notice: "Property updated successfully"
      else
        redirect_back fallback_location: edit_owner_property_path, alert: "Failed to update property"
      end
    end

    def destroy
      @property.destroy
      redirect_to owner_properties_path, alert: "#{@property.name} deleted successfully."
    end

    def update_amenities
      if @property.update!(amenities_params)
        redirect_to edit_owner_property_path, notice: "Amenities updated successfully"
      else
        redirect_back fallback_location: edit_owner_property_path, alert: "Failed to update amenities"
      end
    end

    def update_location
      if @property.update!(location_params)
        redirect_to edit_owner_property_path, notice: "Location updated successfully"
      else
        redirect_back fallback_location: edit_owner_property_path, alert: "Failed to update location"
      end
    end

    def add_images
      @property.images.attach(params[:property][:images])
      redirect_to edit_owner_property_path, notice: "Image added successfully"
    end

    def remove_image
      image = @property.images.find(params[:image_id])
      if image.destroy!
        redirect_to edit_owner_property_path, notice: "Image removed successfully"
      else
        redirect_back fallback_location: edit_owner_property_path, alert: "Failed to remove image"
      end
    end

    private

    def set_property
      @property = current_user.properties.find(params[:id])
    end

    def location_params
      params.require(:property).permit(:latitude, :longitude)
    end

    def amenities_params
      params.require(:property).permit(amenity_ids: [])
    end

    def property_params
      params.require(:property).permit(
        :name,
        :price,
        :headline,
        :description,
        :guest_count,
        :bedroom_count,
        :bed_count,
        :bathroom_count,
        :address_1,
        :address_2,
        :city,
        :state,
        :country_code
      )
    end
  end
end

app/controllers/owner/reservations_controller.rb
module Owner
  class ReservationsController < ApplicationController
    before_action :authenticate_user!

    def index
      @reservations = current_user.properties.map(&:reservations).flatten
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  def show
    @property = Property.includes(:reviews).find(params[:id])
    @overall_rating = @property.reviews.group("ROUND(final_rating)").count.transform_keys(&:to_i)
    @overall_rating.default = 0

    upcoming_reservations = @property.reservations.upcoming_reservations.pluck(:checkin_date, :checkout_date)
    @blocked_dates = upcoming_reservations.map { |reservation| [ reservation[0].to_s, (reservation[1] - 1.day).to_s ] }
  end
end

app/views/owner/properties/_form.html.erb
<div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
  <div>
    <h2 class="text-base font-semibold leading-7 text-gray-900">Property Information</h2>
    <%= form_with model: @property, url: path, class:'mt-6 grid grid-cols-1 gap-x-6 gap-y-8 sm:grid-cols-6' do |f| %>
      <div class="sm:col-span-3">
        <%= f.label :name, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :name, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-3">
        <%= f.label :price, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :price, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="col-span-full">
        <%= f.label :headline, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :headline, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="col-span-full">
        <%= f.label :description, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.rich_text_area :description, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-3">
        <%= f.label :guest_count, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.number_field :guest_count, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-3">
        <%= f.label :bedroom_count, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.number_field :bedroom_count, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-3">
        <%= f.label :bed_count, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.number_field :bed_count, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-3">
        <%= f.label :bathroom_count, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.number_field :bathroom_count, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="col-span-full">
        <%= f.label :address_1, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :address_1, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-4">
        <%= f.label :address_2, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :address_2, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-2">
        <%= f.label :city, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :city, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-2">
        <%= f.label :state, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.text_field :state, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="sm:col-span-2">
        <%= f.label :country, class:'block text-sm font-medium leading-6 text-gray-900' %>
        <%= f.country_select :country_code, class: 'mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-gray-900 sm:text-sm sm:leading-6' %>
      </div>
      <div class="col-span-full">
        <%= f.submit "Save", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
      </div>
    <% end %>
  </div>
</div>

app/views/owner/properties/edit.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  <main>
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Property Images</h2>
        <div class="mt-2 grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-1">
          <% @property.images.each do |image| %>
            <div class="relative w-40 h-40">
              <%= image_tag image, class:'w-40 h-40 object-cover' %>
              <%= button_to remove_image_owner_property_path(image_id: image.id), method: :delete, class:"absolute top-1 right-1 rounded-3xl p-1 bg-white opacity-50" do %>
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                  <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                </svg>
              <% end %>
            </div>
          <% end %>
        </div>
        <%= form_with model: @property, url: add_images_owner_property_path, class:'mt-6' do |f| %>
          <div>
            <div class="">
              <%= f.label 'Add Images', class:'block text-base font-semibold leading-7 text-gray-900 mb-2' %>
              <%= f.file_field :images, class:'font-medum', multiple: true %>
              <%= f.submit "Upload Images", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <%= render 'owner/properties/form', path: owner_property_path %>
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8" data-controller="map">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Google Location</h2>
        <%# TODO: Set initial location by passing the coordinates to js controller. %>
        <%= form_with model: @property, url: update_location_owner_property_path, class:'mt-6' do |f| %>
          <div class="mt-6">
            <div id="map" class="rounded-md h-80"></div>
            <%= f.hidden_field :latitude, data: {"map-target": 'latitude'} %>
            <%= f.hidden_field :longitude, data: {"map-target": 'longitude'} %>
          </div>
          <div class="col-span-full">
            <%= f.submit "Save", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="px-8 py-8 border rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-base font-semibold leading-7 text-gray-900">Amenities</h2>
        <%= form_with model: @property, url: update_amenities_owner_property_path, class:'mt-6' do |f| %>
          <div class="mt-6 grid grid-cols-1 md:grid-cols-2">
            <% Amenity.all.each do|amenity| %>
              <div class="flex items-center gap-2">
                <%= f.check_box :amenity_ids, {class: 'w-6 h-6 mr-2 py-2 rounded-md text-primary focus:ring-primary', multiple: :true}, amenity.id, nil  %>
                <%= render 'properties/amenity_item', amenity: amenity %>
              </div>
            <% end %>
          </div>
          <div class="col-span-full">
            <%= f.submit "Save", class:"cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="px-8 py-8 border border-red-500 rounded-md lg:flex-auto my-8">
      <div>
        <h2 class="text-2xl font-semibold leading-7 text-red-500">Delete Property</h2>
        <p class="my-2">This action is permanent and irreversible. Are you sure?</p>
        <%= button_to 'Delete', owner_property_path, method: :delete, class:"mt-4 rounded p-1 bg-red-500 hover:bg-red-700 text-white px-8 py-2" %>
      </div>
    </div>
  </main>
</div>
<script>
  (g=>{var h,a,k,p="The Google Maps JavaScript API",c="google",l="importLibrary",q="__ib__",m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await (a=m.createElement("script"));e.set("libraries",[...r]+"");for(k in g)e.set(k.replace(/[A-Z]/g,t=>"_"+t[0].toLowerCase()),g[k]);e.set("callback",c+".maps."+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+" could not load."));a.nonce=m.querySelector("script[nonce]")?.nonce||"";m.head.append(a)}));d[l]?console.warn(p+" only loads once. Ignoring:",g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})
      ({key: "AIzaSyD2ebuacUFpGhBftfv4_H2z_9wVucrN7Ns", v: "weekly"});
</script>

app/views/owner/properties/index.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  <main class="px-8 my-8 lg:flex-auto">
    <div>
      <div class="flex justify-between items-center">
        <h2 class="text-2xl font-semibold leading-7 text-gray-900">Properties</h2>
        <%= link_to 'Add Property', new_owner_property_path, class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-2 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2' %>
      </div>
      <div class="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-3 xl:gap-x-8">
        <% @properties.each do |property| %>
          <div class="flex flex-col">
            <%= render 'properties/property_item', property: property, minimal_details: false %>
            <%= link_to 'Edit', edit_owner_property_path(property), class:'cursor-pointer mt-2 flex items-center justify-center rounded-md border border-primary text-primary px-8 py-2 text-base font-medium hover:text-white hover:bg-primary focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2' %>
          </div>
        <% end %>
      </div>
    </div>
  </main>
</div>

app/views/owner/properties/new.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <%= render 'shared/owner_sidebar' %>
  <main>
    <%= render 'owner/properties/form', path: owner_properties_path %>
  </main>
</div>