config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Defines the root path route ("/")
  root "home#index"

  namespace :api do
    resources :wishlists, only: [ :create, :destroy ]
  end

  resources :properties, only: [ :show ] do
    resources :bookings, only: [ :new ]
  end

  resources :booking_payments, only: [ :create ]

  resources :wishlists, only: [ :index ]

  resource :profile, only: [ :edit, :update ]
  resource :email, only: [ :edit, :update ]
  resource :password, only: [ :edit, :update ]

  resources :reservations, only: [ :index ] do
    resources :reviews, only: [ :new, :create ]
  end

  get "/search", to: "search#index"

  namespace :owner do
    resources :properties do
      member do
        patch :update_location
        patch :update_amenities
        patch :add_images
        delete :remove_image
      end
    end
    resources :reservations, only: [ :index ]
  end

  get "booking_payments/success", to: "booking_payments#success"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_reservation, only: [ :create, :new ]

  def create
    @review = current_user.reviews.new(review_params.merge(
      property_id: @reservation.property_id,
      reservation_id: @reservation.id,
    ))

    if @review.save
      redirect_to root_path, notice: "Review added successfully"
    else
      redirect_back fallback_location: root_path, alert: "Failed to add review"
    end
  end

  private

  def set_reservation
    @reservation = Reservation.find(params[:reservation_id])
  end

  def review_params
    params.permit(
      :content,
      :cleanliness_rating,
      :accuracy_rating,
      :checkin_rating,
      :communication_rating,
      :location_rating,
      :value_rating
    )
  end
end

app/views/reviews/_rating_item.html.erb
<div class="flex justify-between py-4">
  <%= f.label category_rating, class:'text-sm font-medium leading-6 text-gray-900' %>
  <div class="flex">
    <%= f.hidden_field category_rating, data: {"rating-target": category_rating} %>
    <% 5.times do |i| %>
      <svg 
        class="fill-gray-300 h-6 w-6 flex-shrink-0 cursor-pointer" 
        viewBox="0 0 20 20" 
        fill="currentColor"
        aria-hidden="true"
        data-action="click->rating#setRating"
        data-category="<%= category_rating %>"
        data-rating="<%= i + 1 %>"
        data-rating-target="star"
        >
        <path fill-rule="evenodd" d="M10.868 2.884c-.321-.772-1.415-.772-1.736 0l-1.83 4.401-4.753.381c-.833.067-1.171 1.107-.536 1.651l3.62 3.102-1.106 4.637c-.194.813.691 1.456 1.405 1.02L10 15.591l4.069 2.485c.713.436 1.598-.207 1.404-1.02l-1.106-4.637 3.62-3.102c.635-.544.297-1.584-.536-1.65l-4.752-.382-1.831-4.401z" clip-rule="evenodd" />
      </svg>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="mx-auto max-w-7xl lg:flex lg:gap-x-16 lg:px-8">
  <main class="px-8 my-8 lg:flex-auto">
    <div>
      <h2 class="text-2xl font-semibold leading-7 text-gray-900">Add Review</h2>
    </div>
    <div class="mt-4 border border-gray-300 rounded-xl p-6 h-min">
      <div class="flex justify-between">
        <%= render 'properties/mini_property_item', property: @reservation.property %>
      </div>
      <div class="relative py-6 mt-4">
        <div class="absolute inset-0 flex items-center" aria-hidden="true">
          <div class="w-full border-t border-gray-300"></div>
        </div>
      </div>
      <div class="max-w-96">
        <%= form_with url: reservation_reviews_path do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :property_id, value: @reservation.property_id %>
          <div class="flex flex-col py-4">
            <%= f.label :content, class:'block text-sm font-medium leading-6 text-gray-900' %>
            <%= f.text_area :content, class:'block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6' %>
          </div>
          <div data-controller="rating">
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "cleanliness_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "accuracy_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "checkin_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "communication_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "location_rating"} %>
            <%= render :partial => 'reviews/rating_item', :locals => {:f => f, category_rating: "value_rating"} %>
          </div>
          <%= f.submit "Submit Review", class:"cursor-pointer mt-4 flex items-center justify-center rounded-md border border-transparent bg-primary px-8 py-3 text-base font-medium text-white hover:bg-primary-dark focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2" %>
        <% end %>
      </div>
    </div>
  </main>
</div>